version: '3.12'

services:
  llm-service:
    build: .
    container_name: llm-container
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: bash -c "pipenv install --system && /bin/bash" #to automatically update pipenv.lock, so that when rebuild no need to pipenv install again
